### PR TITLE
Ft landingpage #160200884

### PR DESCRIPTION
**Pull request by salma-nyagaka**
**What does this PR do?**
Creates a landingpage

**Description of Task to be completed?**

Tasks completed:
-User can view about us, contact and get access 
to the login/sign page

**How should this be manually tested?**

clone the repo as below:
git clone -b ftlandingpage-#160200884 https://github.com/salma-nyagaka/FastFoodFast.git

cd /FastFoodFast/App/landingpage/UI
Open index.html

**What are the relevant pivotal tracker stories?**

https://www.pivotaltracker.com/story/show/160200884

**Screenshots**
landing1
about
contact

### CODE REVIEW

**Comment by mdn-network** [comment]
Good one here.....

**Comment by mdn-network** [comment]
How did you put the transparent background on Fast-Food-Fast?

**Comment by salma-nyagaka** [comment]
In your css styles set the background with 'opacity: 0.9;'

**Comment by ClintMaruti** [comment]
Nice UI

**Comment by mdn-network** [comment]
Thanks will try it out

**Comment by kelvinndmo** [comment]
Nice one salma

**Comment by ThaDeveloper** [comment]
This is really good.

**Pull request closed without merging**
